export const data = [
  {
    id: 1,
    name: 'Dell inspiron',
    picture: 'none',
    category: 'electrionic',
    price: 200,
    avalible: 29,
    inCart: false,
    counter: 0,
  },
  {
    id: 2,
    name: 'laptop Dell',
    picture: 'none',
    category: 'electrionic',
    price: 100,
    avalible: 12,
    inCart: false,
    counter: 0,
  },
  {
    id: 3,
    name: 'laptop Lenovo',
    picture: 'none',
    category: 'electrionic',
    price: 430,
    avalible: 35,
    inCart: false,
    counter: 0,
  },
  {
    id: 4,
    name: 'laptop HP',
    picture: 'none',
    category: 'electrionic',
    price: 750,
    avalible: 19,
    inCart: false,
    counter: 0,
  },
  {
    id: 5,
    name: 'laptop HP',
    picture: 'none',
    category: 'electrionic',
    price: 450,
    avalible: 16,
    inCart: false,
    counter: 0,
  },
  {
    id: 6,
    name: 'laptop HP',
    picture: 'none',
    category: 'electrionic',
    price: 1500,
    avalible: 25,
    inCart: false,
    counter: 0,
  },
  {
    id: 7,
    name: 'laptop Lenovo',
    picture: 'none',
    category: 'electrionic',
    price: 600,
    avalible: 73,
    inCart: false,
    counter: 0,
  },
  {
    id: 8,
    name: 'laptop Lenovo',
    picture: 'none',
    category: 'electrionic',
    price: 700,
    avalible: 42,
    inCart: false,
    counter: 0,
  },
  {
    id: 9,
    name: 'laptop Lenovo',
    picture: 'none',
    category: 'electrionic',
    price: 800,
    avalible: 5,
    inCart: false,
    counter: 0,
  },
];
